### ISSUE TITLE
No module named vigra

### ISSUE THREAD

**Issue by Akhsoul** [rshkarin/quanfima#1]
I cannot proceed beyond the 3rd line (from quanfima import morphology as mrph) as it keeps giving me: Import Error: No module named vigra

**Comment by rshkarin** [comment]
Hi, you can install Vigra (https://ukoethe.github.io/vigra/) using Anaconda package manager as:
```
conda install -c ukoethe vigra
```
If you use buit-in Python, you can try to install it from sources https://github.com/ukoethe/vigra, but I recommend install this package from Anaconda distribution (https://www.anaconda.com/distribution), in this case all packages could be installed from the same place. Please note, that quanfima was tested only for Python 2.7.

**Comment by Akhsoul** [comment]
Hi,

Thank you for your prompt reply. I have been trying to install vigra all
this time. But, it keeps causing me runtime error R6034. I have tried every
re-installing C++ distributions, but it does not help. I would like to try
quanfima, but so far it seems impossible to use for me.

Also, I noticed that python 2.7 will cease to exist next year. Will you be
updating quanfima to python 3?

Best regards,
Alma

**Comment by vansjyo** [comment]
Hi! I tried this package, and since I was getting a lot of errors(using Anaconda) due to incompatible dependencies, I converted the code to python 3 with changes in the version of some of the dependencies. @rshkarin, would you mind if I share the code? I would like to know how you would prefer this?

**Comment by rshkarin** [comment]
Hi! @vansjyo if you could create PR for compatibility with python 3 it would be perfect!

**Comment by vansjyo** [comment]
Ok!  I will get back in a few days.

**Comment by SantiagoQuinteros** [comment]
Hi @vansjyo would really appreciate if you can share the compatible code, thanks!

**Comment by vansjyo** [comment]
@rshkarin I had only changed the code of the files in this url(https://github.com/rshkarin/quanfima/tree/master/quanfima), i.e. the four `.py` files, which makes the code compatible. The requirements also change accordingly. Therefore I would not recommend merging it to the original repo. Perhaps, we could work on a new repository and add the necessary documentation. Please let me know your suggestions on this.

**Comment by rshkarin** [comment]
@vansjyo it would be great if you could share changes via PR, so I could try to integrate it into the main repo and make it compatible for different python versions, so other people could use it.

**Comment by vansjyo** [comment]
@rshkarin please refer https://github.com/rshkarin/quanfima/pull/2

**Comment by Lancelof2019** [comment]
I have installed vigra by using conda create -c conda-forge --prefix=/usr,but when I use python test.py,the error still comes out.

And besides I found there is one function vigra.impex.readImage('testimg.jpg').view(np.ndarray).squeeze(), however I did not find function under installed vigra. In which file  is there readImage?
